[package]
name = "capsule-api"
version = { workspace = true }
edition = { workspace = true }
description = "Public REST API for the Capsule hypervisor"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true }
capsule-core = { workspace = true }
capsule-host-agent = { workspace = true }
capsule-telemetry = { workspace = true }
hashbrown = { workspace = true }
opentelemetry = { workspace = true }
parking_lot = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
subtle = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
tracing = { workspace = true }
tracing-opentelemetry = { workspace = true }
ulid = { workspace = true }

[dev-dependencies]
base64 = { workspace = true }
rand = { workspace = true }
